Fix compilation cordova
[tab_fill]
error TS2339: Property 'annexes' does not exist on type '{ production: boolean; }'.

-Added [' '] around some components related to environment.ts